"""Shelve CR account verification feature

Revision ID: 37eb85bc44b2
Revises: cc6c218f1972
Create Date: 2026-08-04 15:28:06.064718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37eb85bc44b2'
down_revision: Union[str, Sequence[str], None] = 'cc6c218f1972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_challenges_user_id'), table_name='verification_challenges')
    op.drop_table('verification_challenges')
    op.drop_column('users', 'cr_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cr_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('verification_challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('card_one', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('card_two', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('verification_challenges_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_challenges_pkey'))
    )
    op.create_index(op.f('ix_verification_challenges_user_id'), 'verification_challenges', ['user_id'], unique=True)
    # ### end Alembic commands ###
