"""Simplify verification challenge to single favorite card

Revision ID: 929b110177ea
Revises: fa171121ff5d
Create Date: 2026-08-04 00:58:04.154943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929b110177ea'
down_revision: Union[str, Sequence[str], None] = 'fa171121ff5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_challenges', sa.Column('card', sa.String(length=64), nullable=False))
    op.drop_column('verification_challenges', 'card_two')
    op.drop_column('verification_challenges', 'card_one')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_challenges', sa.Column('card_one', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('verification_challenges', sa.Column('card_two', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('verification_challenges', 'card')
    # ### end Alembic commands ###
