"""Revert verification challenge to two-card deck arrangement

Revision ID: cc6c218f1972
Revises: 929b110177ea
Create Date: 2026-08-04 01:05:02.739167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6c218f1972'
down_revision: Union[str, Sequence[str], None] = '929b110177ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_challenges', sa.Column('card_one', sa.String(length=64), nullable=False))
    op.add_column('verification_challenges', sa.Column('card_two', sa.String(length=64), nullable=False))
    op.drop_column('verification_challenges', 'card')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_challenges', sa.Column('card', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('verification_challenges', 'card_two')
    op.drop_column('verification_challenges', 'card_one')
    # ### end Alembic commands ###
