"""Add CR account verification

Revision ID: fa171121ff5d
Revises: 1420377628ab
Create Date: 2026-08-04 00:32:27.962641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa171121ff5d'
down_revision: Union[str, Sequence[str], None] = '1420377628ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_one', sa.String(length=64), nullable=False),
    sa.Column('card_two', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_challenges_user_id'), 'verification_challenges', ['user_id'], unique=True)
    op.add_column('users', sa.Column('cr_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cr_verified')
    op.drop_index(op.f('ix_verification_challenges_user_id'), table_name='verification_challenges')
    op.drop_table('verification_challenges')
    # ### end Alembic commands ###
